version: '3.9'

services:
  application:
    build:
      context: application
      dockerfile: Dockerfile
      args:
        HELM_VERSION: ${HELM_VERSION}
        KUBECTL_VERSION: ${KUBECTL_VERSION}
    volumes:
      - ./application:/code
      - ./credentials:/code/credentials
      - ./.env:/code/.env
    networks:
      - service-network
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres_user:super_secret_password@postgres/service_hub
      TEST_DATABASE_URL: postgresql+asyncpg://postgres_user:super_secret_password@postgres/test
      FILE_STORAGE_ROOT: /tmp
      SECRETS_DIRECTORY: credentials
      ENV_FILE: .env
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - service-network
    ports:
      - '3000:80'
    depends_on:
      - application


  ###
  postgres:
    image: postgres:14.4
    # command: [
    #   'postgres',
    #   '-c', 'log_statement=all',
    #   '-c', 'log_duration=true'
    # ]
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=super_secret_password
      - POSTGRES_DB=service_hub
    ports:
      - '5432:5432'
    volumes:
      - ./docker-data/postgres-data:/var/lib/postgresql/data
    networks:
      - service-network
networks:
  service-network:
    name: service-network
