version: '3.9'

services:
  application:
    image: jovianx/service-hub_application
    networks:
      - service-network
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres_user:super_secret_password@postgres/service_hub
      TEST_DATABASE_URL: postgresql+asyncpg://postgres_user:super_secret_password@postgres/test
      FILE_STORAGE_ROOT: /tmp
      SECRETS_DIRECTORY: credentials
      UI_HOST: http://localhost:3000
      ENV_FILE: .env
    depends_on:
      - postgres

  task-executor:
    image: jovianx/service-hub_application
    command: ./start-task-executor.sh
    networks:
      - service-network
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres_user:super_secret_password@postgres/service_hub
      TEST_DATABASE_URL: postgresql+asyncpg://postgres_user:super_secret_password@postgres/test
      FILE_STORAGE_ROOT: /tmp
      SECRETS_DIRECTORY: credentials
      UI_HOST: http://localhost:3000
      ENV_FILE: .env
      PYTHONPATH: .
    depends_on:
      - postgres
      - application

  frontend:
    image: jovianx/service-hub_frontend
    networks:
      - service-network
    ports:
      - '3000:80'
    depends_on:
      - application

  ###
  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=super_secret_password
      - POSTGRES_DB=service_hub
    ports:
      - '5432:5432'
    volumes:
      - ./docker-data/postgres-data:/var/lib/postgresql/data
    networks:
      - service-network
networks:
  service-network:
    name: service-network
