export const PATHS = {
  ACCESS_TOKENS: 'access-tokens',
  APPLICATIONS: 'applications',
  SERVICES: 'services',
  SERVICE_CREATE: 'services/create',
  CHARTS: 'charts',
  CLUSTERS: 'clusters',
  DASHBOARD: 'dashboard',
  RELEASES: 'releases',
  RELEASE_DETAILS: 'releases/:id',
  REPOSITORIES: 'repositories',
  TEMPLATES: 'templates',
  SIGN_IN: 'sign-in',
  SIGN_UP: 'sign-up',
  SIGN_OUT: 'sign-out',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
};
