apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: application
  name: application
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      component: application
  template:
    metadata:
      labels:
        component: application
    spec:
      containers:
        - name: application
          image: {{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
          env:
            - name: DATABASE_URL
              value: postgresql+asyncpg://postgres_user:super_secret_password@postgres/service_hub
            - name: TEST_DATABASE_URL
              value: postgresql+asyncpg://postgres_user:super_secret_password@postgres/test
            - name: ENV_FILE
              value: .env
            - name: FILE_STORAGE_ROOT
              value: /tmp
            - name: SECRETS_DIRECTORY
              value: credentials
            - name: UI_HOST
              value: http://localhost:3000
          ports:
            - containerPort: 8000
